[window]

padding.x = 0
padding.y = 0
decorations = "Full"
startup_mode = "Maximized"

[font]

size = 18.0

[font.offset]
x = 1
y = 2

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "V", mods = "Control", action = "Paste" },
  { key = "N", mods = "Control", action = "SpawnNewInstance" },
]
